### PR TITLE
Remove the dependency to Gson

### PR DESCRIPTION
**Pull request by k24**
Hello,
Thanks for that nice library.
But Gson is not the only one library to handle JSON, and as is well known, using several libraries for the same purpose is not fitting to build apks, so implicitly depending to such a library is not good.

I remove the dependency to Gson by default because of above, though the compatibility is lost. I hope the implicit dependency is removed anyway, so this request is simply to acknowledge that.

Thanks.

### CODE REVIEW

**Comment by sys1yagi** [comment]
looks good :eyes:

**Comment by gfx** [comment]
I prefer it, even if it breaks backward compatibility.

@rejasupotaro ping?

**Comment by rejasupotaro** [comment]
@k24 That's smart solution! I'll update README after merge this PR > @gfx

**Comment by gfx** [comment]
@k24 I'm sorry https://github.com/cookpad/puree-android/pull/28 conflicts with this yours. Can you merge master to this PR?

**Comment by gfx** [comment]
I'm sorry I have rewrite Puree to use Gson heavily. In fact, Gson's `JsonObject` is more useful than `org.json.JSONObject` so it makes things better.

**Pull request closed without merging**
