### PR TITLE
[Proposal] New interfaces to configure Puree

### PR DESCRIPTION
**Pull request by rejasupotaro**
I'd like to change interfaces to configure Puree. Because

- I don't want to specify `TAG` when I send log
- It's not easy to understand where log is sent

## Before

Destination definition is far apart from sender.

```java
new PureeConfiguration.Builder(context)
    .registerOutput(new OutDisplay())
    .registerOutput(new OutBufferedLogcat(), addEventTimeFilter, samplingFilter)
    .registerOutput(new OutLogcat(), addEventTimeFilter)
    .build();
```

I need to know where I should send logs.
In addition, It's not good that I have to specify output plugin by String.

```java
Puree.send(new ClickLog("MainActivity", "BUTTON 1"), OutDisplay.TAG);
Puree.send(new ClickLog("MainActivity", "BUTTON 2"), OutDisplay.TAG);
...
```

## After

It's easy to understand where log is sent at a glance. 

```java
new PureeConfiguration.Builder(context)
    .source(ClickLog.class).to(new OutDisplay())
    .source(ClickLog.class).filters(addEventTimeFilter, samplingFilter).to(new OutBufferedLogcat())
    .source(PvLog.class).filter(addEventTimeFilter).to(new OutLogcat())
    .build();
```

```java
Puree.send(new ClickLog("MainActivity", "BUTTON 1"));
Puree.send(new ClickLog("MainActivity", "BUTTON 2"));
...
```

It looks simple and intuitive.

screen shot 2015-02-21 at 10 18 41

## Todo

- [x] Change interfaces
- [x] Add tests
- [x] Update documents
- [x] Update v2.0.0

### CODE REVIEW

**Comment by rejasupotaro** [comment]
@sys1yagi @slightair @gfx What do you think?

**Comment by sys1yagi** [comment]
LGTM. :+1:

**Comment by rejasupotaro** [comment]
@sys1yagi @slightair @gfx  Finished. We decided to focus on managing logs in this library. I'll upload to jcenter if there is anything.

**Comment by slightair** [comment]
LGTM :+1:

**Comment by gfx** [comment]
:eyes:

**Comment by rejasupotaro** [comment]
Thanks guys!

**Pull request merged**
